name: smartparking_flutter2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.4+12

environment:
  sdk: ">=2.3.0-dev.0.5.flutter-a1668566e5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.20.0
  firebase_core: ^0.4.0+8
  cloud_firestore: ^0.12.9
  firebase_ml_vision: ^0.9.2
  firebase_auth: ^0.14.0+1
  cloud_functions: ^0.4.1
  in_app_purchase: ^0.2.1
  intl: ^0.15.8
  #image_picker: ^0.6.0+10
  crypto: ^2.1.1+1
  http: ^0.12.0+2
  xml: ^3.3.1
  equatable: ^0.4.0
  flutter_speed_dial: ^1.2.1
  shared_preferences: ^0.5.3+4
  flutter_bluetooth_serial: ^0.2.1
  
  #flutter_bluetooth_serial:
  #  git:
  #    url: git://github.com/PsychoXIVI/flutter_bluetooth_serial.git
  #    ref: issue50_debuging

  #flutter_nfc_reader:
  #  git:
  #    url: https://github.com/akeblom/flutter-nfc-reader
  #    ref: master

  nfc_in_flutter: ^1.2.0     
  qr_flutter: ^2.1.0+55
  image: ^2.1.4
  #barcode_scan: ^1.0.0
  #flutter_markdown: ^0.2.0
  webview_flutter: ^0.3.11
  pin_input_text_field: ^1.0.1
  flushbar: ^1.8.2
  material_design_icons_flutter: ^3.2.3895
  #font_awesome_flutter: ^8.5.0
  android_device_info: ^1.0.0
  device_info: ^0.4.0+2
  percent_indicator: ^2.1.1
  url_launcher: ^5.1.2
  package_info: ^0.4.0+6
  camera: ^0.5.2+2
  path_provider: ^1.2.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/parking.jpg
   - images/appicon.png
   - images/microparking.png
   - images/nfc.png
   - assets/carros.json
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
